CREATE TABLE book(
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL,
    resume VARCHAR(500) NOT NULL,
    isbn VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    year_book timestamp NULL,

    CONSTRAINT book_pkey PRIMARY KEY (id)
);