CREATE TABLE loan (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	loan_time varchar(255) NULL,
  CONSTRAINT loan_pkey PRIMARY KEY (id)
);

--ALTER TABLE book ADD loan_id int8;
--ALTER TABLE book ADD FOREIGN KEY (loan_id) REFERENCES loan(id);